### ISSUE TITLE
ResNet-50-deploy.prototext has 1000 outputs

### ISSUE THREAD

**Issue by pjvance** [yulequan/melanoma-recognition#2]
Thanks for sharing!

On the link provided to download a trained network from onedrive, The 'fc1000' layer has 1000 outputs. Is this correct for the trained model?

layer {
	bottom: "pool5"
	top: "fc1000"
	name: "fc1000"
	type: "InnerProduct"
	inner_product_param {
		num_output: 1000
	}
}

I am attempting to run the model via python and having a little difficulty interpreting the output. Any help would be greatly appreciated.

Many Thanks,
Pjvance

**Comment by yulequan** [comment]
Do you mean the original ResNet-50 network?  The original ResNet-50 for ImageNet has 1000 classes and you should fine-tune (only use the previous feature layers) the network.

**Comment by pjvance** [comment]
Apologies, I had assumed that the pre-trained network provided for download was the network described in the paper. I wished to run the model for myself. So I would need to use the original model and fine-tune using the files provided?

**Comment by yulequan** [comment]
Yes.
